### ISSUE TITLE
How to solve this error

### ISSUE THREAD

**Issue by xubigshu** [mucephi/ffplay#1]
dlopen("/data/app/com.mucephi.vplayer-2/lib/x86/libmain.so", RTLD_LAZY) failed: dlopen failed: could not load library "libavcodec.so" needed by "libmain.so"; caused by could not load library "libcamera2ndk.so" needed by "libavcodec.so"; caused by library "libcamera2ndk.so" not found
2021-12-13 21:49:41.055 13401-13401/com.mucephi.vplayer W/System.err: dlopen failed: could not load library "libavcodec.so" needed by "libmain.so"; caused by could not load library "libcamera2ndk.so" needed by "libavcodec.so"; caused by library "libcamera2ndk.so" not found

**Comment by leonelhs** [comment]
In a glimpse I can see your libcamera2ndk.so has been compiled but it has not been included in to your apk, you need to make the proper changes at your app build.gradle in order to package your new lib besides prebuilt libs.

**Comment by xubigshu** [comment]
I just compiled your source code ~ I didn't introduce my own compiled ffmpeg library～

**Comment by xubigshu** [comment]
The problem has been resolved. The minSdkVersion is too low.
